services:
  postgres_riot:
    image: postgres:15
    container_name: dw_riot_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./Src/05_Load_final/ddl.sql:/docker-entrypoint-initdb.d/1_ddl.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M

  etl_pipeline:
    build: .
    container_name: etl_riot_runner
    env_file:
      - .env
    depends_on:
      postgres_riot:
        condition: service_healthy
    volumes:
      - ./Src:/app/Src
      - ./Logs:/app/Logs

volumes:
  pgdata: